apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-gql
  labels:
    app: client-service-gql
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-service-gql
  template:
    metadata:
      labels:
        app: client-service-gql
        environment: dev
    spec:
      containers:
        - name: client-service-gql
          image: rtecsoft/client-service-gql:0.0.5
          imagePullPolicy: IfNotPresent
          resources: {}
#            limits:
#              memory: "512Mi"
#              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql/ClientDb"
            - name: MYSQL_USER
              value: clientdb_user
            - name: MYSQL_PASS
              value: yourStrong(!)Password
          ports:
            - containerPort: 8080
