apiVersion: v1
kind: Service
metadata:
  name: client-service-lb
spec:
  type: LoadBalancer
  selector:
    app: client-service-gql
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
