apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-service-gql-ingress
  labels:
    app: client-service-gql
    environment: dev
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-service-gql
            port: 
              number: 8080
